# Generated by Django 4.0.3 on 2023-01-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='media/', upload_to='product_images/'),
        ),
    ]
